name: Publish

on:
    push:
        branches: ['master', 'main']

jobs:
    publish:
        name: Publish
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - uses: valitydev/action-frontend/setup@v1
            - run: npm ci
            - uses: valitydev/action-frontend/publish@v1
              with:
                  npm-token: ${{ secrets.NPM_TOKEN }}
