name: Publish

on:
    push:
        branches: ['master', 'main']

jobs:
    publish:
        name: Publish
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
            - uses: valitydev/action-frontend/setup@v1.0
            - run: npm ci
            - uses: valitydev/action-frontend/publish@v1.0
              with:
                  npm-token: ${{ secrets.NPM_TOKEN }}
